### ISSUE TITLE
ATM6 spawn places incorrectly

### ISSUE THREAD

**Issue by RaVenInTheDark** [ModdedMinecraftClub/issue-tracker#10]
When spawning from the first time, you can end up below the spawn area.

**Comment by TraceLD** [comment]
I've tried to fix this multiple times and failed. @john01dav could you take a look?

**Comment by RaVenInTheDark** [comment]
> I've tried to fix this multiple times and failed. @john01dav could you take a look?

I also tried before making the issue.

**Comment by john01dav** [comment]
@TraceLD @RaVenInTheDark What did each of you try?

**Comment by ImVaskel** [comment]
spawn radius can theoretically set you below the spawn.

**Comment by ImVaskel** [comment]
fixed with ```
gamerule spawnRadius 0
```
