### ISSUE TITLE
Incorrect MOTD

### ISSUE THREAD

**Issue by Emiralp26** [ModdedMinecraftClub/issue-tracker#101]
![image](https://user-images.githubusercontent.com/44795814/197358910-63b7706c-1de6-4a02-baa6-1a27c27341a6.png)
Nothing major however, it seems the MOTD of GTNH Ironman states the server is on 2.1.2.0 while it is on 2.2.0.0. Like I said nothing major however just a small thing to fix.

**Comment by merx3d** [comment]
Ahhh I'll fix it after dinner.

**Comment by merx3d** [comment]
fixed
