### ISSUE TITLE
Compact Machine missing insides

### ISSUE THREAD

**Issue by Bishnu82** [ModdedMinecraftClub/issue-tracker#102]
Sunday 11/23 around Midnight I was logged in and all was good.  This morning when I logged in I noticed none of my storage was working.  I had to make a personal shrinking device to check my compact machine and when I got inside it was empty.  I had the Mekanism storage setup and a RS storage system.  Not sure if we can figure out what happened or what to do to fix this.

**Comment by merx3d** [comment]
Compact machine got rebound to a new room somehow, created a cm connected to the correct room
