### ISSUE TITLE
Railcraft Tunnel Bore can not be placed in GTIM

### ISSUE THREAD

**Issue by AbdielKavash** [ModdedMinecraftClub/issue-tracker#103]
There is a known issue in Railcraft where the Tunnel Bore sometimes can not be placed (or rather, breaks immediately when placed). The mod tries to place the bore first at coordinates (0, 0, 0), and then moves it to the player position. However, if the block at (0, 0, 0) is lava or some other invalid block, this breaks the bore before it can be moved, and as a result the player is unable to place it anywhere in the world. See https://github.com/Railcraft/Railcraft/pull/2024.

An obvious workaround is to travel to (0, 0, 0) and remove any offending blocks. I tried doing that, unfortunately on the IM server (possibly others, I haven't checked) the coordinates (0, 0) are claimed by another player (Jonaria). Could an admin please visit these coordinates and check whether there is lava at (0, 0, 0), and if so remove it, so that the bore can be used?

**Comment by merx3d** [comment]
fixed
