### ISSUE TITLE
Recent Grief Resulted in Loss of Chests in my Base, need a Rollback.

### ISSUE THREAD

**Issue by ultranine1** [ModdedMinecraftClub/issue-tracker#105]
During the recent grief of the GTNH servers, I accidentally accepted a tpa from the griefer, who proceeded to kill me and use cheats to drain my claimed chests of items, including quest items I am incapable of reproducing and countless other materials that would take hours of work to recover. I need the chunk at x: -14087, z: 1015 rolled back to 9:00 AM EST, as well as my inventory, which was partially lost. I apologize for the inconvenience.

**Comment by merx3d** [comment]
Rolled your base back last night, waiting for you to get on so I can restore your inv
