### ISSUE TITLE
First RTP to get a home

### ISSUE THREAD

**Issue by Zenthae** [ModdedMinecraftClub/issue-tracker#106]
Yo,
As stated in the title, is it possible to get a first RTP on GTNH IM, so that i can get a place far from the spawn, where i could start my journey to insanity ? I'd like to restart from scratch, and well, i kind of find it meaningless to struggle just to find a place with nobody around.
Thanks

**Comment by Zenthae** [comment]
False said no .... sad

**Comment by Zenthae** [comment]
I'm reopening it, seeing the number of grief, i believe my request is justified.

**Comment by merx3d** [comment]
Well, the server's currently whitelisted so minimal chance of griefers, also not sure on implementation such as if I'd just put a multi year cooldown for it. Thus, for now I'm closing this.
