### ISSUE TITLE
Griefer Emptied chests, need rollback

### ISSUE THREAD

**Issue by DefNotFishu** [ModdedMinecraftClub/issue-tracker#107]
Craban1233444 - who has since been banned - emptied all but one chest in our claimed and/or protected machine/production area between coordinates X-4360 Y-9577 Y75 and coordinates X-4303 Y-9614 Y60. They also emptied all chests in claimed and/or protected storage area between coordinates X-4340 Z-9653 Y-61 and coordinates X-4314 Z-9640 Y69. This was essentially everything we owned and would make the game very hard to play with from this point forward. Would it be possible to have our stuff restored? my IGN is DefNotFishu, my teammates IGNs are Ritone and MiniMeni. My Discord is Fishu#0001 for any questions

**Comment by ritone** [comment]
Happened again 5:45am est can you also rollback inventory of ritone(me) same area thanks

**Comment by merx3d** [comment]
base was first rolled back by falsecurrency for initial issue and thenn base and inv was rolled back by duckhemp for added comment
