### ISSUE TITLE
egorch123 grief 

### ISSUE THREAD

**Issue by ritone** [ModdedMinecraftClub/issue-tracker#109]
They emptied a lot of  chests and barrels in claimed and/or protected storage area between coordinates X-4312 Z-9655 Y-60 and coordinates X-4355 Z-9600 Y70.

**Comment by ritone** [comment]
Teammates are defnotfishu and menimeni/meowimeni
my ign is ritone discord is (=_=)#9707 feel free to msg me for questions

**Comment by merx3d** [comment]
base and inv was rolled back by duckhemp
