### ISSUE TITLE
My grave ate my wireless crafting terminal

### ISSUE THREAD

**Issue by teufler80** [ModdedMinecraftClub/issue-tracker#114]
I died and my wireless crafting terminal wasn't in the grave
Inside the terminal was my infinity booster card which is the worst loss.
Adding screenshot as proof that i had the infinity booster card

![image](https://user-images.githubusercontent.com/34612967/200127206-3279011c-9e91-4e65-a649-78cc6971147c.png)

IGN is Teufler80

**Comment by teufler80** [comment]
ID for the terminal is 9908
ID for the booster card is 9906

**Comment by MeniMeniMeni** [comment]
Refunded!
