### ISSUE TITLE
Gravestone Glitch Items Lost on GTNH

### ISSUE THREAD

**Issue by SapphireBlaze** [ModdedMinecraftClub/issue-tracker#116]
As I was remodelling my tinkers smeltery I managed to die in what metal was still in there, I thought little of it until I broke the gravestone and seemingly half ofmy inventory including my pickaxe and my newly acquired Axe of Healing voided out of existence. 

My Minecraft Usernames is : SapphireBlxze and the gravestone was at -3929, 9672, 72 coordinates, this was on the basic GregTech New Horizons server

**Comment by merx3d** [comment]
restored several days ago, closing this
