### ISSUE TITLE
Items lost due to breaking of my Grave

### ISSUE THREAD

**Issue by Emiralp26** [ModdedMinecraftClub/issue-tracker#117]
I accidentally shot myself while trying to kill mobs. And after trying to retrieve my grave when I broke it due to me having too much stuff in my inventory, some stuff in my inventory disappeared.

Before:
![image](https://user-images.githubusercontent.com/44795814/202865180-1ae0341f-d6b0-4b66-8b7e-43a6134cd75d.png)

After:
![image](https://user-images.githubusercontent.com/44795814/202865189-b15429dc-cf94-438f-9580-1e055bdb37f1.png)

This happened on 19/11/2022 around 12:49 PM EST. I would love for a backpack, healing axe, glider, and the rest of the stuff that I am missing to be restored.

**Comment by Emiralp26** [comment]
I don't know how I have not noticed but I have the backpack I just need my backpack and the glider that's all. Thank you! No need to restore my playerdata

**Comment by merx3d** [comment]
We can restore the whole thing if that's what you're wanting or are you just wanting that glider back?

**Comment by Emiralp26** [comment]
The healing axe and the glider should do the trick.

**Comment by merx3d** [comment]
![2022-11-20_01 43 35](https://user-images.githubusercontent.com/22422630/202891390-11aef9f6-a4f6-418a-8bb4-a40086f5e6c9.png)
completed.
