### ISSUE TITLE
Server deleted many many ores instantly 

### ISSUE THREAD

**Issue by ashido96** [ModdedMinecraftClub/issue-tracker#121]
I broke a gold chest that I store my ores in to replace with a diamond chest and the server basically instantly deleted 70% of the ores. 

Please restore ores created by overagressive cleanup operation at approximately 3:45 CST - (9:45 GMT), thank you. 

I believe the coordinates of the chest are: -1215, -1151, y=83

![image](https://user-images.githubusercontent.com/2313143/206031591-acb60ee0-2136-4a2a-869e-6fcdcbf45a30.png)

**Comment by ashido96** [comment]
I guess just rolling back that one block? (possible idk?) to when it was a gold chest around that time would accomplish same thing. I haven't touched it.

**Comment by merx3d** [comment]
I'll have to rollback the whole area, grab the chest and undo the rollback

**Comment by ashido96** [comment]
> I'll have to rollback the whole area, grab the chest and undo the rollback

Okay I'll take a break for today. Thank you very much.

**Comment by ashido96** [comment]
Resolved: Thank you very much!
