### ISSUE TITLE
Stone block 3 issue- Grave glitched out, didn't return items when broken

### ISSUE THREAD

**Issue by Myrtox** [ModdedMinecraftClub/issue-tracker#123]
Died a few items on the same spot, after clearing area broke two graves, one on top of the other, no items were returned from either grave.

I believe issue was due to soul sand causing me to sick below a grave when I died.

PS. no category for SB3, sorry.

**Comment by merx3d** [comment]
Do you still have the obituary from when you died with all of your items on you?

**Comment by merx3d** [comment]
Want me to close this issue? I don't know if you want those items restored still or if it was fixed already.

**Comment by Myrtox** [comment]
> Do you still have the obituary from when you died with all of your items on you?

Sorry you can close. I remade almost everything in the end. Only thing missing is the repair token. 

Thanks,
