### ISSUE TITLE
I cant verify my client!

### ISSUE THREAD

**Issue by JackAttackGB** [ModdedMinecraftClub/issue-tracker#125]
![image](https://user-images.githubusercontent.com/40872866/208816739-59a23efd-81e0-4307-8510-23b7c94301bf.png)
No matter what device I use or what account I use I still end up with the same problem of my Clint not able to be verified.

**Comment by merx3d** [comment]
From some brief research your issue is related to minetogether, there's mostly speculation as to what's causing it aside from the chat moderation bot being overzealous. Check if something's weird with your account on their website.

**Comment by JackAttackGB** [comment]
I cant do much from the website, other than logging and says thank you for logging in. It's all just super buggy.

**Comment by merx3d** [comment]
Sorry man been a bit busy with work recent so I haven't had time to respond, most likely your best bet would be to get in contact with their support team as we can't do much to fix that on our end.

**Comment by merx3d** [comment]
Did you manage to get this worked out with their support team?

**Comment by merx3d** [comment]
Can't fix on our end so let me know if you need help with anything else, can reopen if needed.
