### ISSUE TITLE
Gravestone glitch loss

### ISSUE THREAD

**Issue by SusanS2022** [ModdedMinecraftClub/issue-tracker#126]
Happy New Year.

I ended up dying by a warp lightning strike, that is not the concern. The reason for this request is when I went to pick up my gravestone and due to the glitch that it has, I lost my oxygen breathing gear.

Is there any chance I can get this gear replaced, Thanks

Items Needed:
1 x Oxygen Mask
1 x Oxygen Gear
1 x Frequency Module
1 x Medium Oxygen Tank

Susan

**Comment by merx3d** [comment]
Did you ever get these items restored?

**Comment by merx3d** [comment]
closed as stale and we can reopen it if you still need these replaced
