### ISSUE TITLE
Move Me Please

### ISSUE THREAD

**Issue by Bishnu82** [ModdedMinecraftClub/issue-tracker#127]
I think my character RBurgandy got in a bad spot.  Was hopping you could just warp me to start.  Thanks

![Screenshot 2023-01-19 122351](https://user-images.githubusercontent.com/55993943/213516070-1dd3901e-7d35-4960-9fd9-1c66627cb0ad.png)

**Comment by merx3d** [comment]
Thank you so much for bringing this to my attention, something else actually happened that caused it. Hopefully, you should be able to login now that it's fixed. Though, nothing processed since you left due to the other issue.

**Comment by Bishnu82** [comment]
Thanks I got in
