### ISSUE TITLE
Broken blocks that I didn't break.

### ISSUE THREAD

**Issue by CyborgCreeper** [ModdedMinecraftClub/issue-tracker#13]
About 20+ minutes ago I heard ice break nearby and found a area that had some packed ice broken and I just now realize my front door is missing and a bunch of blocks are broken as shown in screenshots. They seemed to be invisible cause I saw running particles at one point and tried to follow them but of course couldn't find them. (They didn't show on the mini map either.
![2022-03-22_16 03 10](https://user-images.githubusercontent.com/28032343/159566636-3d9b6588-b065-421b-b1aa-cd546046421a.png)
![2022-03-22_16 03 19](https://user-images.githubusercontent.com/28032343/159566639-0535afb7-ea46-4839-8cdb-81cfb47a1822.png)
![2022-03-22_16 03 23](https://user-images.githubusercontent.com/28032343/159566641-7f65a716-8b50-4c28-9cc9-06c1a1363617.png)
![2022-03-22_16 06 04](https://user-images.githubusercontent.com/28032343/159566642-311d7705-4d64-4964-b7d9-e66fa9fcc56c.png)

**Comment by CyborgCreeper** [comment]
For reference my door was a "Dungeon Door" and its height is 4 blocks and width is 3 block

**Comment by RaVenInTheDark** [comment]
Is your area claimed?

**Comment by CyborgCreeper** [comment]
Yes it is

**Comment by CyborgCreeper** [comment]
Does the server have any plugins that show block history of people breaking them?

**Comment by CyborgCreeper** [comment]
And I know for a fact I did break the blocks in the second to last picture.

**Comment by CyborgCreeper** [comment]
Problems fixed by john.
