### ISSUE TITLE
[GTNH tp] [LOW-LEVEL] claim transfer

### ISSUE THREAD

**Issue by Struckboot** [ModdedMinecraftClub/issue-tracker#130]
I need a claim transfer from player "GuntherNinja" to "Struckbot", or just having GuntherNinja's claim unclaimed. I believe he hasn't logged in for atleast 3 months, and says he won't be playing GTNH anymore. 

Coords: | x:2269, z:20892, overworld

Ingame name: Struckbot

**Comment by merx3d** [comment]
Permission granted by original owner of the claim

**Comment by merx3d** [comment]
transfer complete
