### ISSUE TITLE
TPS issues on NFC

### ISSUE THREAD

**Issue by JEngel05** [ModdedMinecraftClub/issue-tracker#131]
Lots of TPS issues on NFC:
```
[1/1] Command forge tps's output
Output message
Dim 0 (overworld) : Mean tick time: 2338.109 ms. Mean TPS: 0.428
Dim 2 (Storage Cell) : Mean tick time: 0.039 ms. Mean TPS: 20.000
Dim 119 (JED Surface Loaded 0) : Mean tick time: 20.015 ms. Mean TPS: 20.000
Overall : Mean tick time: 2371.770 ms. Mean TPS: 0.422
Today at 2:12 PM
```

This seemed to happen as I got close to Aluxxen's claim.  There may be something dumping all over the ground in the area.  I will attach some screenshots of where I was when the tps problems started.
![2023-02-20_14 21 29](https://user-images.githubusercontent.com/28551149/220197294-9e3f787e-feb5-4bab-b646-6b4533f7d0d9.png)
![2023-02-20_14 21 34](https://user-images.githubusercontent.com/28551149/220197304-a0c72e4b-6f9b-487b-aa94-f61f79f23b46.png)

**Comment by merx3d** [comment]
I'll look at it but no promises I'll be able to isolate the issue, though I have some ideas

**Comment by JEngel05** [comment]
I've also noticed that a lot of times the lag starts when someone logs off.  It's almost as if some things in their area stay chunk loaded while other's don't and it causes a lot of stress on the server.  Maybe just bumping up the auto-restarts to be more frequent would help as the lag always is gone after restart.

**Comment by JEngel05** [comment]
More info:
When "bcbuckles" logs out, the TPS problems immediately start.  It's fine when he's logged in and playing.  Something funky with his area that wrecks havoc on the server when he logs out.
