### ISSUE TITLE
Crashloop due to item in inv/hand username: ritone

### ISSUE THREAD

**Issue by ritone** [ModdedMinecraftClub/issue-tracker#134]
I tried to craft the Wireless map from WR-CBE and as i put it into my inventory it crashed me and now joining crashes me.
If there is a way to delete that item from my inventory that would be great otherwise I can join and be /killed or whatever will get me bac on gtnh.

**Comment by merx3d** [comment]
Will fix, just the the item id

**Comment by ritone** [comment]
It's 10960

**Comment by ritone** [comment]
oops didn't mean to close
