### ISSUE TITLE
I think my character needs to be moved back to start again

### ISSUE THREAD

**Issue by Bishnu82** [ModdedMinecraftClub/issue-tracker#136]
The usual error I get randomly.  If you could please move my character back to the home spot thanks.  
![image](https://user-images.githubusercontent.com/55993943/227823699-49bb6b4b-94bc-4bcb-a1db-6e3334d6a653.png)

**Comment by merx3d** [comment]
You're all good now right? with the rollback fixing your character's location

**Comment by Bishnu82** [comment]
Yes I am sorry I did not close this issue.
