### ISSUE TITLE
Sever disappear 

### ISSUE THREAD

**Issue by Mgmbccu** [ModdedMinecraftClub/issue-tracker#140]
I was playing into sb3 server when i was kicked of couse server connection lost. So i tried to login again but the sever disappear form the public server list ? what can i do for fix ? is a problem of my game or is just server down for some update ?

**Comment by merx3d** [comment]
The server appears to have crashed and will be back up shortly

**Comment by Mgmbccu** [comment]
okay okay so is only crushed, thanks u a lot..

**Comment by merx3d** [comment]
The server is now back online.
