### ISSUE TITLE
Bigger Reactor voids fuel and energy in battery

### ISSUE THREAD

**Issue by lslinnet** [ModdedMinecraftClub/issue-tracker#141]
I am seeing the issue described in https://github.com/BiggerSeries/BiggerReactors/issues/71 in my reactor, i have roughly loaded 2k uranium ingot's into my reactor and it seems to be voiding it either when I leave the server, server restart or similar unload + load situations of the chunk.

I will try and rebuild the reactor shortly, but just giving a heads up here that there is a voiding bug.

**Comment by lslinnet** [comment]
IGN: Gloombone

**Comment by merx3d** [comment]
gotcha, thanks for heads up on this

**Comment by merx3d** [comment]
fixed in the update
