### ISSUE TITLE
ATM 8 - Copy/Paste Building Gadget ate my upgrades

### ISSUE THREAD

**Issue by Bishnu82** [ModdedMinecraftClub/issue-tracker#143]
I wanted to turn my phytogenic insolator area and thought the copy paste tool from Building Gadgets would be the quickest way.  So I copied it knocked everything down rotated it how I wanted and when I paste it all the upgrades on my drawers and insolators are gone.

Thermal Series - Phyto's lost -
4 x Draconic Integral Component
30 x Resonant Integral Components
30 x Hardened Integral Components

Functional Storage - 1x2 Drawers lost - 
30 x netherite upgrade

**Comment by merx3d** [comment]
Request completed. please close this when you have confirmed it
![image](https://github.com/ModdedMinecraftClub/issue-tracker/assets/22422630/bd8c4ac1-48b7-4ade-be14-0a0ce39e39a9)

**Comment by Bishnu82** [comment]
Thank you items received.
