### ISSUE TITLE
FTB Skies issue

### ISSUE THREAD

**Issue by faenormp** [ModdedMinecraftClub/issue-tracker#144]
it seems like the loot bee is supposed to spawn at the start of your island, this doesn't seem to be the case for my group. Is it possible we could have one forcibly spawned? I don't know if it does drop something needed for progression or what, but maybe we could just get that quest unlocked as well

team should be: KingFaenor's team with members KingFaenor, _Kyrin, and avid3113

**Comment by merx3d** [comment]
answered via discord chat, bee spawning is a random chance event
