### ISSUE TITLE
E2E grave disappeared

### ISSUE THREAD

**Issue by dagamincrusadr** [ModdedMinecraftClub/issue-tracker#145]
I was killed by a dragon and can't find my grave, it's not at the location of my death waymark. At the moment I am trying to excavate the walls of the cave to see if its in there somewhere but I'm having trouble since there is a dragon. Not sure if the grave spawning in walls is a common thing/known issue or if it just didn't spawn a grave.

**Comment by dagamincrusadr** [comment]
I found the grave, it was inside the walls probably 20 blocks away from where I actually died

**Comment by merx3d** [comment]
Hi,

Please let us know if you're missing any items or need anything replaced from this grave bug.

Thanks!
