### ISSUE TITLE
Machine bug and disappearance

### ISSUE THREAD

**Issue by WildHunt3r** [ModdedMinecraftClub/issue-tracker#146]
I was breaking a Lathe Machine MV with my Wrench when it was dropping normally but I had a lag and it disappeared.
Date: July 22 in the morning

Is it possible to do anything?

**Comment by merx3d** [comment]
Sure, just let me know a good set of coords to drop off a replacement for you, you can send me a dm on discord if you don't want to post them here -falsecurrency

**Comment by WildHunt3r** [comment]
The coord is X : 2256, Y : 65, Z : 13297
Thank you :D

**Comment by merx3d** [comment]
gave you the missing lathe, please let us know if there's anything else we can help you with
