### ISSUE TITLE
All the mods 8 dns resolve failure

### ISSUE THREAD

**Issue by fingin** [ModdedMinecraftClub/issue-tracker#149]
within my and another players mine-craft client, we are unable to ping the atm8 server nor connect to it, as we can connect to the other servers we believe that the issue is with dns resolution, standing by for updates

**Comment by HeatherComputer** [comment]
What error do you get upon trying to connect?

If it is a DNS error, entering `s4.moddedminecraft.club:25599` may solve the issue.

**Comment by merx3d** [comment]
Hi,

Due to the age of this issue, so that we may better manage the issue repository, we will be closing this issue for now. If this issue still persists or assistance is required, please feel free to reopen this ticket.

Thank you!
