### ISSUE TITLE
Conduits

### ISSUE THREAD

**Issue by CyborgCreeper** [ModdedMinecraftClub/issue-tracker#15]
I tried to make a conduit twice and both times it dropped nothing, I followed the recipe fully. 4 Nautilus shells, 2 Fluorite, 2 Lapis, Source gem, and Heart of the sea, then strike with lightning.

**Comment by RaVenInTheDark** [comment]
Ping me when you're online and I'll give you the conduits.

**Comment by john01dav** [comment]
They came online when you were not so I spawned it for them.
