### ISSUE TITLE
Tombstone bug

### ISSUE THREAD

**Issue by Warre1gn** [ModdedMinecraftClub/issue-tracker#150]
Username: Warreign

My grave seems to miss a few items, namely nano goggles of rev., nano boots of traveler, energetic alloy limb-thaum binding-Flame bowstring-damascus steel body crossbow with a maxed lapis and redstone (I think the level was like 12). Upon breaking the grave I immediately picked up an active magnet, so I think it is very unlikely that the items just flew off somewhere.

**Comment by merx3d** [comment]
Please confirm that all 3 items you requested to be refunded have been refunded as requested and placed in item frames at your base for collection.

**Comment by Warre1gn** [comment]
Everything is resolved now
