### ISSUE TITLE
Really for TNP 7 but no option for that - Lost items

### ISSUE THREAD

**Issue by Bishnu82** [ModdedMinecraftClub/issue-tracker#151]
I broke a diamond Shulker and a Diamond Barrel both from Sophisticated storage and they were both full of mainly armor and weapons.  Was hopping to get it returned if possible.  Thanks

**Comment by merx3d** [comment]
Hey Burgandy, sorry. With the way the barrels are stored ingame, in order to restore them effeciently, I'd need to rollback the area to a point where they're either on the ground or rollback your playerdata to a time when you have them on hand. I can if you would like.

**Comment by Bishnu82** [comment]
Nah I moved on.  I think I talked to False about this and just forgot to close the ticket sorry about that.
