### ISSUE TITLE
Data wipe

### ISSUE THREAD

**Issue by Zenthae** [ModdedMinecraftClub/issue-tracker#152]
Hello, can I get a data on both GTNH server ? I'd like to start from fresh!

**Comment by Zenthae** [comment]
And still keep my member rank, btw !

**Comment by merx3d** [comment]
Hey Zen,

I'm sorry this has taken so long, I plan to look into what needs to be done for a full wipe sometime Wednesday afternoon so I ensure I don't botch it.

**Comment by Zenthae** [comment]
ok, thx, take your time

**Comment by merx3d** [comment]
Oh, also I need you to login and state that you consent to having your inventory wiped, quests reset and thaumcraft progress reset.

**Comment by Zenthae** [comment]
In the end, I won't be playing on MMCC for GTNH, I got whitelisted on officials and will be playing there. Sorry for wasting your time.
