### ISSUE TITLE
TNP7 Crash loop 

### ISSUE THREAD

**Issue by geareh** [ModdedMinecraftClub/issue-tracker#153]
Hi, thanks for taking your time to look at this.

Today I have encountered a crash loop after playing for a few hours. Moved my base to a new location and when I got all the chests and machines placed and sorted I seem to be encountering a crash loop. I have crashed multiple times on retrying to enter the server. However the crash is not instant on connecting. Usually it takes  up to 2 or 3 minutes. I will try removing blocks around my base to trouble shoot which could be causing issues here. Though considering these are all items I had placed in a previous base location for the past week, I am skeptical of that being the issue. 

Included below is a crash dump.
Any help here would be appreciated

Thanks,
Geareh

[crash-2023-10-15_15.27.13-client_geareh.txt](https://github.com/ModdedMinecraftClub/issue-tracker/files/12909816/crash-2023-10-15_15.27.13-client_geareh.txt)

**Comment by Tenchu98** [comment]
ok this appears to have something to do with the backpack and the compacting upgrade, but I am not sure if it's trying to compact something it shouldn't or not

**Comment by geareh** [comment]
I haven't added a compacting upgrade. So that's strange. Perhaps the upgrade was the bag when I looted it from a mob

**Comment by geareh** [comment]
I have attached a screenshot of my inventory including the troublesome diamond backpack

![image](https://github.com/ModdedMinecraftClub/issue-tracker/assets/147992535/ecb09163-b877-42e3-9c09-b72684cdfb19)

**Comment by HeatherComputer** [comment]
https://www.curseforge.com/minecraft/mc-mods/functional-storage/files/4798172

I'd suggest trying this - though keep a backup of your outdated jar, as I'm not 100% sure if the mod versioning difference will let you connect. Let me know how that goes please

**Comment by geareh** [comment]
This has seemed to fixed my crash loop, thank you! I have been sat idle now in base with occasionally flying close by and chest/backpack openings randomly. I wont get my hopes up entirely just yet. I will stay connected while I am watching the rugby world cup and see what happens etc

**Comment by HeatherComputer** [comment]
Good to hear! I'll leave the issue open for now, but hopefully it's all resolved.

**Comment by HeatherComputer** [comment]
also pinning in case anyone else has the issue before it ges fixed with a pack update.
