### ISSUE TITLE
TNP7 Quarry Plus

### ISSUE THREAD

**Issue by Dalskidan** [ModdedMinecraftClub/issue-tracker#154]
Hi
Im just wondering if there is a config thats limits Quarry plus NORMALs (not chunk destroyer) mining speed or is there a bug on the server. I have 4.5kRF/t going into the quarry and it goes at the same pace as my old power source that was 800RF/t.

If there is a server limit i just want to know or if there is a problem here

**Comment by merx3d** [comment]
Hi Dalskidan, 

The max power inputs per quarry type are as below, the config does not properly describe what each line in it does however so I'm unsure of the exact effects power input has. Theoretically it should scale but I also know that regular quarries are enchantable with efficiency.

Mini Quarry:  maxEnergy = 1000.0
Quarry:  maxEnergy = 10000.0
Advanced Quarry:  maxEnergy = 50000.0
