### ISSUE TITLE
TP7 Can't open my gravestone 

### ISSUE THREAD

**Issue by Herkulion** [ModdedMinecraftClub/issue-tracker#157]
Hello, i died today in nether and cant open my gravestone, right clicking with key or sneaking does not work

**Comment by merx3d** [comment]
Please advise if this has been resolved or is still a pending issue.

**Comment by merx3d** [comment]
Hi,

Due to the age of this issue, so that we may better manage the issue repository, we will be closing this issue for now. If this issue still persists or assistance is required, please feel free to reopen this ticket.

Thank you!
