### ISSUE TITLE
Removing GT_Cover_LiquidMeter with crowbar crashes game

### ISSUE THREAD

**Issue by Nitromo** [ModdedMinecraftClub/issue-tracker#16]
Using a crowbar on a Fluid Hatch to remove a Fluid Detector Cover occasionally crashes my game
(I'm new to github; hoping the crash reports are attached properly)

[crash-2022-03-14_15.04.20-client.txt](https://github.com/ModdedMinecraftClub/issue-tracker/files/8357471/crash-2022-03-14_15.04.20-client.txt)
[crash-2022-03-15_20.39.25-client.txt](https://github.com/ModdedMinecraftClub/issue-tracker/files/8357472/crash-2022-03-15_20.39.25-client.txt)
[crash-2022-03-16_21.32.30-client.txt](https://github.com/ModdedMinecraftClub/issue-tracker/files/8357473/crash-2022-03-16_21.32.30-client.txt)
[crash-2022-03-27_03.16.25-client.txt](https://github.com/ModdedMinecraftClub/issue-tracker/files/8357474/crash-2022-03-27_03.16.25-client.txt)
[crash-2022-03-27_12.05.02-client.txt](https://github.com/ModdedMinecraftClub/issue-tracker/files/8357475/crash-2022-03-27_12.05.02-client.txt)
[crash-2022-03-27_13.23.42-client.txt](https://github.com/ModdedMinecraftClub/issue-tracker/files/8357476/crash-2022-03-27_13.23.42-client.txt)
e

**Comment by bombcar** [comment]
I’ll check but I believe this was reported upstream and will be fixed in the next release (will be a bit before that’s on our server as releases are usually 6mo timescale)

**Comment by bombcar** [comment]
This is fixed in dev, but it'll be awhile before the next release.
