### ISSUE TITLE
Crash caused by witchery?

### ISSUE THREAD

**Issue by SteynTielemans** [ModdedMinecraftClub/issue-tracker#161]
[crash-2023-12-02_14.40.07-client.txt](https://github.com/ModdedMinecraftClub/issue-tracker/files/13536409/crash-2023-12-02_14.40.07-client.txt)

**Comment by merx3d** [comment]
Hi,

Due to the age of this issue, so that we may better manage the issue repository, we will be closing this issue for now. If this issue still persists or assistance is required, please feel free to reopen this ticket.

Thank you!
