### ISSUE TITLE
This is not related to the discord bot, but please add a Issue tab for Feed the Factory.

### ISSUE THREAD

**Issue by Baronjackass** [ModdedMinecraftClub/issue-tracker#163]
Ive been having this issue (in FTF), that Ive been kicked after a few seconds every time I try to join for a while now. I dont know how to fix it, the internet is stable on my part and I dont have similar issues with other modpacks or servers. I even tried reinstalling. Nothing helps.
[latest.log](https://github.com/ModdedMinecraftClub/issue-tracker/files/13628473/latest.log)

**Comment by merx3d** [comment]
Hi,

Due to the age of this issue, so that we may better manage the issue repository, we will be closing this issue for now. If this issue still persists or assistance is required, please feel free to reopen this ticket.

Thank you!
