### ISSUE TITLE
Feed the factory, insulated mv wires

### ISSUE THREAD

**Issue by zozo5002** [ModdedMinecraftClub/issue-tracker#166]
All of the insulated MV wires in the base turned into LV uninsulated copper wires after server restart

**Comment by zozo5002** [comment]
Update: Another server restart caused the issue again even though I replaced them all one time with mv wires, currently replacing them with conduits but I'm leaving the issue up for others to not bother with mv wires.

**Comment by merx3d** [comment]
Hi,

Due to the age of this issue, so that we may better manage the issue repository, we will be closing this issue for now. If this issue still persists or assistance is required, please feel free to reopen this ticket.

Thank you!
