### ISSUE TITLE
[T7 Chunks rarely not saved

### ISSUE THREAD

**Issue by BDJslime-UnaverageJoe** [ModdedMinecraftClub/issue-tracker#167]
Need a request to restore my grave from my latest death in Bumblezone dimension.
There seems to be some issue with the server not saving chunks when unloaded, causing regression when returning as if any changes are undone, which also applies to death graves. This is not unique to the custom dimension as I observed it in the overworld while using warping commands.

**Comment by BDJslime-UnaverageJoe** [comment]
Items were manually restored but the issue hasn't been checked yet, leaving this issue open.

**Comment by merx3d** [comment]
Hi,

Due to the age of this issue, so that we may better manage the issue repository, we will be closing this issue for now. If this issue still persists or assistance is required, please feel free to reopen this ticket.

Thank you!
