### ISSUE TITLE
request for renewal of access to the residence due to change of nick

### ISSUE THREAD

**Issue by HKal888** [ModdedMinecraftClub/issue-tracker#168]
Hello. I used to play on a server:
Server: MMC No TP(EU+Asia2)
Modded Minecraft Club - Gregtech:NH v.2.3.0.0
 Under the nickname Hkal. Recently I wanted to play again but due to the transfer of my account from Monjang to Microsoft I lost my nick on Microsoft was already taken and I had to change it. From Hkal to Hkal88. Would it be possible to transfer the residences that are on the server under the new nickname Hkal88 or do I have to start over from the beginning? I have added a friend on that residence who played with me under the nickname: DZoneCZ and he can verify that it's me. 

I've been waiting 30 days to check if my nick is impossible to get back. And unfortunately it is. When the option to rename the nick in Minecraft finally opened again, the nick Hkal already exists so I could not get it back.

**Comment by merx3d** [comment]
Based on an investigation to verify your identity, the claim has been transferred and I have transferred your quest progress also to ensure no progress is lost as it is tied to your account's UUID. Please confirm before this ticket is closed.

**Comment by HKal888** [comment]
yes almost everything has been transferred. i only lost my progress in thaumacraft but it doesn't matter research is what i enjoy most in thaumacraft. thank you

**Comment by HKal888** [comment]
I can also arrange for the transfer of second base on the coordinates? x: 6381 y:87 z:4223
