### ISSUE TITLE
Remove the Beediddy Bee from ATM6

### ISSUE THREAD

**Issue by teufler80** [ModdedMinecraftClub/issue-tracker#17]
Its not fun its just insanely frustrating to ranomly loose your armor.
It happened twice for me, you cant kill it and it is naturally aggro to players

**Comment by teufler80** [comment]
![image](https://user-images.githubusercontent.com/34612967/160281472-56209345-f3d0-479b-b0c9-ae0130917702.png)

**Comment by RaVenInTheDark** [comment]
I agree to be honest. Anyone else?

**Comment by teufler80** [comment]
Ok if you enchant indestructible on gear even they cant break it
A massive pain in the butt but possible

**Comment by TraceLD** [comment]
They should be disabled the next time the server restarts.
