### ISSUE TITLE
TNP7 Grave did not load in the Aether

### ISSUE THREAD

**Issue by TheLivingScam** [ModdedMinecraftClub/issue-tracker#170]
Hello,

My grave and the key disappeared the moment i returned to the Aether. Is that an issue that is present or does that work as intended? This was in a Valkyrie dungeon which the blocks are considered unbreakable, though i haven't checked if you are able to place blocks (like the grave).

**Comment by merx3d** [comment]
Hi,

Due to the age of this issue, so that we may better manage the issue repository, we will be closing this issue for now. If this issue still persists or assistance is required, please feel free to reopen this ticket.

Thank you!
