### ISSUE TITLE
minecraft tnp limitless 7

### ISSUE THREAD

**Issue by Wolfcyod** [ModdedMinecraftClub/issue-tracker#171]
I put on the ring of seven curses and i got the unholy ring and jumped into a large body of lava in the nether and it still is on my character are you able to help me

**Comment by merx3d** [comment]
Hi,

Due to the age of this issue, so that we may better manage the issue repository, we will be closing this issue for now. If this issue still persists or assistance is required, please feel free to reopen this ticket.

Thank you!
