### ISSUE TITLE
Blocks disappear

### ISSUE THREAD

**Issue by Sovieton19** [ModdedMinecraftClub/issue-tracker#172]
Every block I break just disappears. Even crops that I harvest. Sometimes the blocks show for a second but then disappear.

**Comment by thejims** [comment]
Encountering the same..  almost like entities are being killed/destroyed instantly..

**Comment by merx3d** [comment]
Hi,

Due to the age of this issue, so that we may better manage the issue repository, we will be closing this issue for now. If this issue still persists or assistance is required, please feel free to reopen this ticket.

Thank you!
