### ISSUE TITLE
TNP 7 Grave bug

### ISSUE THREAD

**Issue by Kevinflo55** [ModdedMinecraftClub/issue-tracker#174]
yo me and my friend Zw3ny21 died on the server he in the end and me nether and now we cant get back our stuff bc the key is not working pls help

**Comment by merx3d** [comment]
Hi,

Due to the age of this issue, so that we may better manage the issue repository, we will be closing this issue for now. If this issue still persists or assistance is required, please feel free to reopen this ticket.

Thank you!
