### ISSUE TITLE
ATM9 - Please enable the Random Teleport command for players

### ISSUE THREAD

**Issue by Myrtox** [ModdedMinecraftClub/issue-tracker#175]
ATM9 is gated behind finding some structures for the upgrade templates and certain mobs/bosses. Many of these structures are either chunk claimed, or destroyed.

This is particularly difficult in The Other dimension, where there is no flight.

I know we have /rtp at spawn, in the overworld, but can we please enable it for players to do via chat commands? And can we set the distance? 

Thanks,

**Comment by Tenchu98** [comment]
By default we disable it to reduce lag from players spamming it. Also exploring to find the structures is part of the packs design and we always attempt to not alter the progression if it is unnecessary.
