### ISSUE TITLE
ATM9 Stuck falling through void.

### ISSUE THREAD

**Issue by adam4826** [ModdedMinecraftClub/issue-tracker#176]
Once i finally get in from the "encrypting" screen it loads me into a void where it looks like im falling and chat commands dont work. then sometimes it loads my char in and i cant open anything or break things. then it crashes.

[crash-2024-04-03_12.21.04-client.txt](https://github.com/ModdedMinecraftClub/issue-tracker/files/14860709/crash-2024-04-03_12.21.04-client.txt)

**Comment by merx3d** [comment]
Hi,

Due to the age of this issue, so that we may better manage the issue repository, we will be closing this issue for now. If this issue still persists or assistance is required, please feel free to reopen this ticket.

Thank you!
