### ISSUE TITLE
ExxonMobil Chemical Plant won't run with Catalyst Housing

### ISSUE THREAD

**Issue by Nitromo** [ModdedMinecraftClub/issue-tracker#18]
I tried to craft RP-1 Rocket Fuel. The Chemical Plant wouldn't start with the Catalyst Housing installed. Is that a bug? The recipe doesn't require a catalyst, but I would think it should work with the Housing anyway.

**Comment by bombcar** [comment]
IIRC there is a minor bug in 2.1.2.0 (what we're on) - try putting a catalyst housing with any catalyst, it should run but not use it.

**Comment by Nitromo** [comment]
It runs for the RP-1 Rocket Fuel without the Housing, just took me a long time to try it without the Housing.

Finally managed to find the issue on GTNewHorizons-github (would have saved me a lot of block swapping if I had found it before :) ) https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9173
