### ISSUE TITLE
No Ender Zoo mobs on GTNH

### ISSUE THREAD

**Issue by thejims** [ModdedMinecraftClub/issue-tracker#181]
Haven't seen any Ender Zoo mobs on the GTNH server in forever, and in particular the Ender Fragments they drop are required for Ender Shards to create a lot of the Blood Magic teleposer.

**Comment by merx3d** [comment]
Hi,

Due to the age of this issue, so that we may better manage the issue repository, we will be closing this issue for now. If this issue still persists or assistance is required, please feel free to reopen this ticket.

Thank you!
