### ISSUE TITLE
[Monifactory] Encryption takes 30 seconds to a minute on loading, once the game loads in latency is at 50k ms, and I get booted with a java.net socket exception when it drops to 19k ms

### ISSUE THREAD

**Issue by RainbowTrenchcoat** [ModdedMinecraftClub/issue-tracker#182]
This applies with the standard and alternate server IP addresses. Even if I stand completely still with f3 on, the boot still happens, so it's not a discord bot issue.
![image](https://github.com/user-attachments/assets/8ecc5c99-0181-41d9-bc9e-037f92700734)

**Comment by merx3d** [comment]
Hi,

Due to the age of this issue, so that we may better manage the issue repository, we will be closing this issue for now. If this issue still persists or assistance is required, please feel free to reopen this ticket.

Thank you!
