### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Excellius00** [ModdedMinecraftClub/issue-tracker#184]
Hi, Server seems to crash whenever I try to join,

IGN is Excelluiss.

Didn't have any issue's last night when I logged off. Seems to be something in the twlight forest

**Comment by merx3d** [comment]
Hi,

Due to the age of this issue, so that we may better manage the issue repository, we will be closing this issue for now. If this issue still persists or assistance is required, please feel free to reopen this ticket.

Thank you!
