### ISSUE TITLE
TNP Limitless 7: Unable to join server

### ISSUE THREAD

**Issue by KyranAwesome1500** [ModdedMinecraftClub/issue-tracker#185]
So i have been playing on this server for a bit now and whist flying around spawn i entered the area of someones base and now i cant join the server. Actually everytime i join the server it crashes. i enjoy playing on this server and i hope someone helps me get out of these corrupted chunks,
![server closed](https://github.com/user-attachments/assets/5a39a6a3-91ca-4cb4-ac17-ba9fb14bbebd)
![Server crashed](https://github.com/user-attachments/assets/82e9823e-65fe-489d-aa96-786e5a320a1c)

**Comment by merx3d** [comment]
Hi,

Due to the age of this issue, so that we may better manage the issue repository, we will be closing this issue for now. If this issue still persists or assistance is required, please feel free to reopen this ticket.

Thank you!
