### ISSUE TITLE
Monifactory - Unable to join server

### ISSUE THREAD

**Issue by zrrkd** [ModdedMinecraftClub/issue-tracker#186]
This happened after RTPing, can someone send me back to spawn? 
Ign: Zrrkd

![image](https://github.com/user-attachments/assets/6359d89e-aa3b-4adf-8ce0-a75f29bcc973)

**Comment by zrrkd** [comment]
https://pastebin.com/Ffv2meW5

**Comment by merx3d** [comment]
Apologies for the delay, you should be good to go.
