### ISSUE TITLE
[Suggestion] More chunks loadable

### ISSUE THREAD

**Issue by Skip21** [ModdedMinecraftClub/issue-tracker#19]
Just to give a bit of context : 

E6E's Early game and a lot of crafts throughout the entire playthrough require some Create machinery and thus a lot of room. 
And when you get deeper into the modpack you also need to have partial bases around the different dimensions that are available (e.g. Blood Magic requires to be done in The Undergarden until you get a Master Blood Orb)

With 18 chunks loadable and those chunks scattered accross the different dimensions you end up with a small amount of chunks left to load your Overworld base.

This is why I came here to ask if increasing the amount of chunks loadable for E6E's members could be a thing.

Thanks a lot for considering my suggestion.

**Comment by john01dav** [comment]
Raven has told me that this is done.
