### ISSUE TITLE
I get an error when trying to join A6 server.

### ISSUE THREAD

**Issue by kamichhi** [ModdedMinecraftClub/issue-tracker#23]
When I use the intended version of A6 (1.8.20) and try to join the server it gives me the error "Failed to synchronize registry data from server, closing connection" Im using the GDLauncher, my java version is 1.8.0_321 if you need anything else, contact me on discord Kamichhi#6073
![4345a0cf50aade8e0a1802701b7a9e13](https://user-images.githubusercontent.com/103587347/163211764-04bc6c43-7d9f-4bd8-8565-3726e57a6e89.png)

**Comment by john01dav** [comment]
In closing this since you said that you're able to join.
