### ISSUE TITLE
Yolo Bucket infinity bucket nbt

### ISSUE THREAD

**Issue by Xashz** [ModdedMinecraftClub/issue-tracker#24]
![image](https://user-images.githubusercontent.com/102233271/163510648-988d403a-5ed3-44e8-885c-f27191d73321.png)
Hello ,

the nbt of the infinity bucket used to make sink had a problem and it was fixed in 1.1.2 update but the old ones dont work still , can i please get a change to the new nbt ones that work for the everlasting spring thats used to make the sink . 

Thank You.

**Comment by RaVenInTheDark** [comment]
Fixed once the player affected was available ingame.
