### ISSUE TITLE
Steam doesn't get recognized in quests - Plat-line

### ISSUE THREAD

**Issue by Nitromo** [ModdedMinecraftClub/issue-tracker#25]
Hi,
could you complete quest #2306 and #2881 for me. None of the variants of steam cells get recognized by the quest.

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9621

![Second Separation - Ruthenium #2306](https://user-images.githubusercontent.com/102466908/163576697-92b93cd8-6773-4a70-8411-8a0e991dcca9.png)

![Heat it up! #2881](https://user-images.githubusercontent.com/102466908/163576717-f14c47dd-8b04-4848-822b-339f0d85763e.png)

**Comment by bombcar** [comment]
Sure - it will take me a bit to get on. 

Have you tried using the ic2 cells? A normal cell in crafting and then fill the resultant with steam?

**Comment by Nitromo** [comment]
Yup, tried the ic2 cells too. No need to rush, I will go back to procrastinating the plat-line :)

**Comment by Nitromo** [comment]
Username: Nitrom

**Comment by Nitromo** [comment]
My first issue-link was missing the last digit (1). I edited my issue, but that wrong issue ( Thaumcraft Research Bug #962 ) still shows that I mentioned it here. Can I remove that somehow? Or do people ignore mentions anyway?

**Comment by bombcar** [comment]
It'll be ignored, no worries.

**Comment by bombcar** [comment]
These should be completed.

**Comment by Nitromo** [comment]
I'm on Ironman

**Comment by bombcar** [comment]
lol

**Comment by bombcar** [comment]
Ok after restart will check on IM - I think I got one in

**Comment by Nitromo** [comment]
I saw Ruthenium completed

**Comment by bombcar** [comment]
There we go. (And if you ever do GT you'll probably have them complete lol)
