### ISSUE TITLE
Unable to spawn ender dragon

### ISSUE THREAD

**Issue by lslinnet** [ModdedMinecraftClub/issue-tracker#27]
The End is missing the center bedrock thingy to allow for spawning the dragon and no dragon is there.

**Comment by lslinnet** [comment]
Further review of this also shows that the regular end portals to get away from the center island is not there.

**Comment by Tenchu98** [comment]
Exit portal has been replaced, ND ender dragon can be spawned.

**Comment by lslinnet** [comment]
Thanks!
