### ISSUE TITLE
Alfsteel Aiot said no to existing

### ISSUE THREAD

**Issue by kamichhi** [ModdedMinecraftClub/issue-tracker#29]
My Alfsteel Aiot (Level S) said no to existing and its not in the world anymore, is it possible to get it back? (IGN: BackTrax)

**Comment by kamichhi** [comment]
![image](https://user-images.githubusercontent.com/103587347/163903605-576b7aa4-66be-45df-bc41-8a358e9f827e.png)

Proof of completing the quest

**Comment by Tenchu98** [comment]
I left the item in a chest next to your bed.
