### ISSUE TITLE
GTNH Ironman griefing

### ISSUE THREAD

**Issue by Cray22** [ModdedMinecraftClub/issue-tracker#3]
IGN: Cray132
Server: GTNH:IM
Location:  x: -5673 z: 5115

I haven't been on a server for quite some time (roughly June) so I have no idea how long has it been like this but my place has been griefed at some point. There was a water creeper explosion inside which ended up blowing up some MV and HV machinery inside even though those chunks were and still are claimed. 

There is a single unclaimed chunk (there used to be a pump there and I forgot to claim it after moving the pump) where there are some changes, new chests to be exact. The chunk is located at roughly x: -5673 z: 5115. Additionaly there are some tracks placed inside, I don't remember doing that. Maybe Steve's carts working around the protection? There are also some random blocks placed around crops island north of the base. 

My pump, basing combustion generator and probably HV fluid tank at x: -5983 z: 5164 have also been stolen.

As a side note: I can't add any labels when writing this message, I'll see if I can add them after submitting the issue.

**Comment by john01dav** [comment]
I have added the appropriate labels, but next time please add appropriate labels to an issue when creating it.

**Comment by bombcar** [comment]
Do you know if there are any other players nearby? I’m not at my desk but if there are a region restore will be bit more complicated (have to do chunk by chunk)

**Comment by Cray22** [comment]
No idea, I don't think there used to be any those few months back. Also no worries, there's no need for rush.

**Comment by Cray22** [comment]
![2022-03-19_22 23 58](https://user-images.githubusercontent.com/101950652/159138874-7fcc2e93-e85f-472b-b7f2-4cc85e02a575.png)
Looks like I may have found the person behind water creeper

**Comment by bombcar** [comment]
This base is on a region boundary, but the regions are empty, and so

```
r.-11.10.mca
r.-12.9.mca 
r.-12.10.mca
r.-11.9.mca
```

have been rolled back to the earliest in our backups. However, that may not be early enough, and initial checking seems to show the water creeper damage - can you check?

**Comment by bombcar** [comment]
If it is no good let me know, I'll return it to how it was before the restore and we can work out the next steps.

**Comment by Cray22** [comment]
Looks like it's just as you've said so you can revert those changes (or you don't have to if it's too much husstle).

The only valuable things missing are those MV and HV machines. Based on the quests those were:
MV: electrolyzer, laser engraver, mixer, chemical reactor, fluid extractor, fluid solidifier, assembling machine, extruder, bender, dehydrator, forming press, 
HV: assembling machine, macerator, chemical reactor, mixer

**Comment by Cray22** [comment]
Sorry, wrong button :P

**Comment by Cray22** [comment]
The screenshots of questboo
![2022-03-21_22 07 25](https://user-images.githubusercontent.com/101950652/159364973-3ba0147f-38c1-46cb-9564-601f7c4e57e7.png)
![2022-03-21_22 07 27](https://user-images.githubusercontent.com/101950652/159364978-cd967572-da90-44c9-a5b0-e730fe0d510b.png)
k

**Comment by bombcar** [comment]
Ok I have rolled back the rollback - if you want please claim a large area around your base (claims can be large when nobody's around) and I will get on soon and add a chest with the items listed.

**Comment by bombcar** [comment]
You should now find a chest in your claim (center room underground) with the items above.

Please claim a large area around your base, and you should be good to go. If everything's fine, you can close this.

**Comment by Cray22** [comment]
Thank you, will do
