### ISSUE TITLE
Item Vanished while away

### ISSUE THREAD

**Issue by Tryanide** [ModdedMinecraftClub/issue-tracker#30]
After moving my base I went for a break and when I had come back my ME Drive had just left the chat along with pretty well every item I had with it.
![2022-04-17_21 45 21](https://user-images.githubusercontent.com/25085748/163784958-3127d2a4-ff47-4068-a9b9-3262d6c076e2.png)
![2022-04-17_21 45 23](https://user-images.githubusercontent.com/25085748/163784950-bd19a22a-9f3f-4801-b869-278a3eb0ddd1.png)

**Comment by john01dav** [comment]
What sort of resolution are you looking for? The main options are a roll back or manual respawn of the lost items.

**Comment by Tryanide** [comment]
Eh I'll probably just call it a day I doubt there is anyway to roll back only a certain area to a time I'm not aware of and I'm not about to try and get 1000's of items back I'll just go play something else, others admins response in discord sounded more hopeful, I've lost all my one off and late game items right before actually finishing the pack not really going backwards now.

**Comment by john01dav** [comment]
I don't mean to sound unhelpful. sorry that I did. It's just that those are the two options that I know of. If you are done with this pack, I understand though. It is possible to roll back a 512x512 area. We take backups every 24 hours at 6:00 AM CET. If you want the rollback, please just let me know.

**Comment by john01dav** [comment]
As it seems that you have left, I'm closing this. If you want to return, feel free to re-open it.
