### ISSUE TITLE
Coming back from Asteroids to coords around 48000,50000

### ISSUE THREAD

**Issue by Nitromo** [ModdedMinecraftClub/issue-tracker#33]
I did travel a few hundred blocks in the Asteroids dimension and my base is 7000 blocks out, but I landed back in overworld 50000 blocks out. I think that is a bug.
I didn't look at my coordinates in the Asteroid dimension, so I don't know if my miner is thousands of blocks of course there already. I can't look at waypoints in Asteroid-Dimension from overworld (I think) and I kinda don't want to fly back there right now.

**Comment by Nitromo** [comment]
I flew to the asteroids from that point again and landed even further out, then flew back to overworld and came out at only 12000, something is very weird here

![Asteroids](https://user-images.githubusercontent.com/102466908/165388212-ed706be9-f072-4e21-bb26-25d0781ccae3.png)

I'm on Ironman, I can't just go with /sethome

**Comment by bombcar** [comment]
Something is strange - I can get you home but it's likely to do it again, not sure why.

Launch pads on both ends might mitigate it (the one that makes the rocket work like a portal)

**Comment by Nitromo** [comment]
there is still my Ore drill tier 2 up there though

**Comment by bombcar** [comment]
We can recover that too, if you can find the coordinates. I can't get online today but tomorrow should work.

**Comment by Nitromo** [comment]
I have a waypoint there, yes. Okay, I'll wait

**Comment by bombcar** [comment]
Let me know if you can get online today; I'm available.

**Comment by Nitromo** [comment]
I worked a bit longer, I'm here now.

I am at my base and crafted the launch controller (and I think I get how it works), would just need a teleport in the Asteroids dimension to the miner

That could wait longer if you are out of time

**Comment by bombcar** [comment]
Looks like that worked!
