### ISSUE TITLE
Steam Cells in quest Synthetic Rubber #1615

### ISSUE THREAD

**Issue by Nitromo** [ModdedMinecraftClub/issue-tracker#34]
Another quest where steam cells don't work. That quest locks the bacterial vat quest which I would like to get to.

username: Nitrom
quest: Synthetic Rubber        #1615

**Comment by bombcar** [comment]
```
>bq_admin complete 1615 Nitrom
[22:42:00 INFO]: Completed quest §9§lSynthetic Rubber for Nitrom
```
