### ISSUE TITLE
GTNH bug with equipping a Personal healing nanobooster

### ISSUE THREAD

**Issue by Revolver27** [ModdedMinecraftClub/issue-tracker#37]
When i equip a Personal healing nanobooster (ID: 9424) in my baubles slot it kicks me from the server with error: internal server error.
I need to equip it in my amulet slot of baubles for it to work, just having it in my inventory wont kick me but it will also not work then.
Currently its fixed by a admin doing /kill while i join so its not in my baubles slot anymore. In singleplayer it works just fine.
Modpack is GTNH and ign revolver275.

**Comment by john01dav** [comment]
I have added the appropriate label to this issue. In the future, please add labels for new issues via an issue template to ensure that it goes to the right person.

**Comment by Duckgrass** [comment]
This is a known issue with GT++ and seems to be fixed in more recent updates.
Doesn't seem like we can do anything about it for the current pack version.
link to the fixing in the gt++ github: https://github.com/GTNewHorizons/GTplusplus/pull/118
