### ISSUE TITLE
Infusion Claw crashes server

### ISSUE THREAD

**Issue by Nitromo** [ModdedMinecraftClub/issue-tracker#38]
Is there a way to grant the claw permission in my claim?

On a previous server I was playing was the command /AutoTrust and everything that interacted in the claim in the next 30 seconds gained permissions.

**Comment by Duckgrass** [comment]
This is an issue with grief prevention on the server not wanting to permit fake players.
We have investigated this issue and configurations pertaining to it, but nothing seems to fix the issue.
The only real solution is to have the fake player work in a non-claimed area. We will ensure to respond to any issues that will cause.
(Closing the issue for now. Let us know if you find anything on your end or run into other claim issues)
