### ISSUE TITLE
Server crashing when I telepot to my Create tunnel machine

### ISSUE THREAD

**Issue by AnnualCassette** [ModdedMinecraftClub/issue-tracker#39]
At about 5:50 PM CST 05/10/2022 I teleported to my Create tunnel machine that's in the Atum dimension and the server hung for a while. Duckhemp restarted the server after a few minutes. Never officially crashed. After it rebooted it rolled back to before I had teleported so at about 6:15 PM same day I teleported again. Server officially crashed and rebooted itself.

If anyone can drop the crash log or help me troubleshoot this it'd be appreciated. Last time I was on, a few weeks ago, the tunnel machine was working fine. There isn't anything else built in the area so assuming whatever it is is from the tunnel machine. Sadly I don't have the cords for the machine. It could be just coincidence but out of respect for the other people online I don't really wanna test it.
Both times I teleported the rails and minecart visually loaded but not the machine itself.

IGN: HaphazardCrytpid
Discord Username: Defined Suffering, am on the MMCC Discord

**Comment by john01dav** [comment]
I have changed a Forge setting, and you may be able to go there without issue after the next restart. If you could test that that would be great (try not to have anything valuable in your inventory at the time, and try not to do it when many people are on). If this fails, I can reset the area. To get coordinates if needed, what do you use to teleport there? Is it a /home?

**Comment by AnnualCassette** [comment]
Was able to hop on with nobody else on. At about 2:40 CST 05/16 teleported to the tunnel machine and server still crashed. Coordinates are: X: -4967, z: 4552, y: 29(1). And yeah, I use a /home, I think it's /home atum miner.
Many thanks for the help!
