### ISSUE TITLE
E6E rtp in end and nether

### ISSUE THREAD

**Issue by CyborgCreeper** [ModdedMinecraftClub/issue-tracker#4]
IGN: Cyborg_creeper
Modpack: E6E
Anytime /rtp is used in nether or end it sends you way far outside of the border. You cannot get damaged outside of the border that far out and cannot mine, can still fight mobs.
![2022-03-19_17 08 25](https://user-images.githubusercontent.com/28032343/159138459-d17d3fff-0b86-446f-8ebd-7b2884dc70c1.png)

**Comment by RaVenInTheDark** [comment]
Should be fixed. Do let me know if it isn't, of course.
