### ISSUE TITLE
No AE2 Certus Quartz on the DW20 server

### ISSUE THREAD

**Issue by razborsek** [ModdedMinecraftClub/issue-tracker#41]
On the new DW20 server there is no Certus Quartz ore from AE2. I used a digital miner in the OW, mining dim and the nether, but no luck. Tried it in SP and found loads. I don't think it spawned when the world was generated. IDK it this was intentional or not, but I would suggest resetting the mining dimension and adding the ore in or adding like a alternative recipe to the game.

**Comment by john01dav** [comment]
This issue has been resolved via new crafting recipes.
