### ISSUE TITLE
Mekanism cables do not connect

### ISSUE THREAD

**Issue by Zaplaro** [ModdedMinecraftClub/issue-tracker#43]
Universal cables from Mekanism do not connect to my IC2 machines

**Comment by john01dav** [comment]
Is this behavior different on the server than in single player? If it is like this in single player than it is either a pack bug, in which case it should be reported to the pack's creators, or intended behavior.

**Comment by john01dav** [comment]
By your lack of response I infer that you no longer care about this issue. If you do, please feel free to reopen it with the answer to my previous question.
