### ISSUE TITLE
OpenComputer robots dont work in claims

### ISSUE THREAD

**Issue by teufler80** [ModdedMinecraftClub/issue-tracker#45]
I try to use a cropfarm with a computercraft robot.
It works fine without a claim, but if i use it inside a claim it wont work.
Is something broken with the permissions ?
I added it as fake player in my claim as well

**Comment by Duckgrass** [comment]
This is an issue with grief prevention on the server not wanting to permit fake players.
We have investigated this issue and configurations pertaining to it, but nothing seems to fix the issue.
The only real solution is to have the fake player work in a non-claimed area. We will ensure to respond to any issues that will cause.
(Closing the issue for now. Let us know if you find anything on your end or run into other claim issues)
