### ISSUE TITLE
application 

### ISSUE THREAD

**Issue by Willcannonward** [ModdedMinecraftClub/issue-tracker#46]
[staff application MMCC.txt](https://github.com/ModdedMinecraftClub/issue-tracker/files/8787095/staff.application.MMCC.txt)

**Comment by Willcannonward** [comment]
Sorry about the hassle, I haven't made many posts/ replies on github,so I
wasn't quite sure how it worked. I do hope you find what you're looking for
within my application. If not I would still love to be of assistance any
way possible.

**Comment by john01dav** [comment]
Unfortunately we need to deny this application.
