### ISSUE TITLE
Perpetually Low TPS on E6E

### ISSUE THREAD

**Issue by aspiringLich** [ModdedMinecraftClub/issue-tracker#48]
there was under 8 TPS on E6E when only I was online, and i highly doubt its my gigachad mega base with only 2 chunks being force-loaded. I think it's due to chunks being force loaded while the players are offline. Would it be possible to reset loaded chunks, or set it to only chunkload while theyre online? thanks.

**Comment by Duckgrass** [comment]
issue was actually fixed. but also the pack is retired
