### ISSUE TITLE
E6E cannot find certain biomes with natures compass due to border

### ISSUE THREAD

**Issue by CyborgCreeper** [ModdedMinecraftClub/issue-tracker#5]
IGN: Cyborg_creeper
Modpack: E6E

The border restricts access to biomes that do not currently exist within the borders confines. Like the marsh, mountain biome and its variants, birch hills, etc. 
Due to this people cannot obtain the Adventuring time advancement.

**Comment by CyborgCreeper** [comment]
Also I can't seem to either figure out how to add labels or I don't have permission.

**Comment by RaVenInTheDark** [comment]
I'll double the border, should fix the issue but let me know if it doesn't suffice.
