### ISSUE TITLE
[Crash] Crash caused by carry on mod and chisel and bits

### ISSUE THREAD

**Issue by FallenMeteor** [ModdedMinecraftClub/issue-tracker#50]
I was playing with chisel and bits and accidentally I shift right-clicked the chisel block causing it to be picked up by the carry on mod. That caused my client to crash, as well as my friend's who was also nearby.
I can't connect to the server as my client crashes instantly.
[crash-2022-05-30_12.47.22-client.txt](https://github.com/ModdedMinecraftClub/issue-tracker/files/8797725/crash-2022-05-30_12.47.22-client.txt)

**Comment by FallenMeteor** [comment]
thanks for reading this @RiiC0Chet

**Comment by john01dav** [comment]
What date/time exactly (in CET) did the crash first take place at? I can roll back your player data file to before then.

**Comment by FallenMeteor** [comment]
May 29th at around 8pm (CET)

**Comment by john01dav** [comment]
I've rolled back your player data. Feel free to re-open this issue if it doesn't work.
