### ISSUE TITLE
Gravestone did not give my items back when I broke it 

### ISSUE THREAD

**Issue by RiiC0Chet** [ModdedMinecraftClub/issue-tracker#51]
I died fighting with blazes when i broke it, and when i came back there wasnt any gravestone with my stuff, only the obituary.
![image](https://user-images.githubusercontent.com/73385995/170984955-d8940adc-1e71-4564-aa58-4a524618a03d.png)
![image](https://user-images.githubusercontent.com/73385995/170985073-501118e6-f2d3-4318-a877-883a24c8b676.png)
![image](https://user-images.githubusercontent.com/73385995/170985132-02a38c09-a154-4b41-9221-eaa97c6a32d5.png)
![image](https://user-images.githubusercontent.com/73385995/170985159-67f1bef9-b5c6-42d2-9f7a-eb535c589cd1.png)

**Comment by john01dav** [comment]
We can spawn these items and give them back. What coordinates would you like them to be left at?

**Comment by RiiC0Chet** [comment]
> We can spawn these items and give them back. What coordinates would you like them to be left at?

I have already put doble chest at -438/971900. Thanks you.

**Comment by john01dav** [comment]
I have gone to x -438, y 97, and z 1900 and there is no double chest there.

**Comment by john01dav** [comment]
I'm closing this due to lack of response to my question. Feel free to re-open it if you get around to responding.
