### ISSUE TITLE
Dimensions have been reset and regenerated, /home's deleted, and map data deleted 

### ISSUE THREAD

**Issue by Myrtox** [ModdedMinecraftClub/issue-tracker#52]
Dimensions have been reset and regenerated, /home's deleted, and map data deleted on E6E after it was brought back online after attempts were made to improve tps and server performance.

**Comment by Duckgrass** [comment]
Have restored the files deleted previously that would be causing the issue. Have tested homes, quests, and dimensions and they appear to be restored from backup.

**Comment by Myrtox** [comment]
> Have restored the files deleted previously that would be causing the issue. Have tested homes, quests, and dimensions and they appear to be restored from backup.

Looks good. Thanks for the quick response and also for looking into the performance issues. We really appreciate your efforts!
