### ISSUE TITLE
[DW20 1.18.2] Sophisticated Backpack lost some of my items.

### ISSUE THREAD

**Issue by evglaceon** [ModdedMinecraftClub/issue-tracker#54]
I was putting stuff in my backpack with a copper upgrade it in [stack size 64 -> 128], and I hit sort so that it would look nice in there. It split a lot of my stacks back into a stack size of 64, and I lost a lot of different metal ingots, lapis and redstone dust. I had roughly 256 copper ingots, 138 redstone dust, 95 tin ingots, 84 nickel ingots, 107 lapis, 145 lead ingots 192 aluminum ingots, and I believe that's about it. I might have gotten some numbers wrong, but I know I had at least a stack of 64 of each and then some, because that's why I was putting them in there to begin with. If anything can be done about it I would be extremely grateful. My IGN is Ev_Glaceon, I am also in the discord if you have any questions.
EDIT: Also 78 Osmium Ingots.

**Comment by Duckgrass** [comment]
Refunded items in a chest at base.
