### ISSUE TITLE
Didnt get my Member rank

### ISSUE THREAD

**Issue by Zaplaro** [ModdedMinecraftClub/issue-tracker#55]
Idk if this is the right place to post this, but i play on Direwolf20. I applied for Member a few days ago and got accepted, but i still am no Member ingame...

**Comment by john01dav** [comment]
What's your IGN?

**Comment by Zaplaro** [comment]
Its already fixed, forgot to close the case

David Johnson ***@***.***> schrieb am Mo., 6. Juni 2022,
04:45:
