### ISSUE TITLE
Fossil Bait recipe bugged - Need the item spawned for me

### ISSUE THREAD

**Issue by JEngel05** [ModdedMinecraftClub/issue-tracker#56]
I tried crafting this twice with the lightning crafting recipe.  The Blood magic alchemy progress is gated behind this item.  

Both times, it ate all components and did not provide the completed item.

Can someone please spawn this item in game and give it to ArsFrags?  Or leave it in a chest at 1555, 1785, 64.

This is the bugged recipe:
![image](https://user-images.githubusercontent.com/28551149/172070424-f72a9777-fbb0-40c1-b33b-f4bc21e1ce99.png)

**Comment by westfallk** [comment]
Gave your player the item. The give command uses meetyourfight:fossil_bait for staff reference.

**Comment by Duckgrass** [comment]
Gave your player the item. The give command uses meetyourfight:fossil_bait for staff reference.
