### ISSUE TITLE
Direwolf20 update not supported

### ISSUE THREAD

**Issue by Aiden636** [ModdedMinecraftClub/issue-tracker#58]
Just updated Direwolf20 to v 1.4.0
Receiving the following error:
"This modded server is not impl compatible with you modded client. Please verify your forge version closely matches the server. Got net version 3 this server is net version 2"

**Comment by john01dav** [comment]
Yes, the server is currently on version 1.3.0, so using a client on version 1.4.0 will not work. You need to download client version 1.3.0. Feel free to create a new issue if you want to request that the server be updated.
