### ISSUE TITLE
Claimed / force chunkloaded chunks limit for Member too low on ATM6

### ISSUE THREAD

**Issue by TraceLD** [ModdedMinecraftClub/issue-tracker#6]
It has been brought to my attention that the limit for claimed/force chunkloaded claims on ATM6 is too low for the member rank (iirc 8).

**Comment by john01dav** [comment]
I asked some members and they said that it's 18. Guests have 8 so maybe that was mixed up somewhere? Someone a little earlier in the chat said that it also gives the appropriate number of claimed chunks. Feel free to re-open this if this isn't actually solved.

https://discord.com/channels/251491739322286081/531628386691579916/955277889601945620
