### ISSUE TITLE
FTB Chunks Map is broken 

### ISSUE THREAD

**Issue by spokosjr** [ModdedMinecraftClub/issue-tracker#60]
Minimap is gone, and whenever you press the map button your game crashes. This is a server side issue since it works perfectly on other servers running the same version of the pack (1.4.1). This is a game-breaking bug since you don't only loose the use of the map but also the ability to claim and chunkload an area.

**Comment by john01dav** [comment]
We reset the server and are on a new pack version, so if this keeps happening please 1) reopen this issue, and 2) upload a client-side crash report.
