### ISSUE TITLE
Nether Reset

### ISSUE THREAD

**Issue by BillyBobJoe12345** [ModdedMinecraftClub/issue-tracker#67]
The area in the nether near where our teams nether portal is has been ender quarried making resource gathering more annoying than usual

**Comment by Duckgrass** [comment]
Apologies for a month-long response.
Do you still need assistance with this issue?
We should be able to restore the region file to world seed generation, but that might destroy tunnels or other things you've built in that area.

**Comment by Duckgrass** [comment]
I will be closing this issue assuming you've found your way around it.
You can re-open it if you do need help.
