### ISSUE TITLE
DW20 Item Refund

### ISSUE THREAD

**Issue by H20Slicer** [ModdedMinecraftClub/issue-tracker#69]
1X Infinity Drill, Tier: Epic
1X Infinity Hammer, Tier: Epic
1X Infinity Trident, Tier: Epic
1X Infinity Backpack, Tier: Epic
1X Mob Duplicator
1X Mob Crusher
5X Soul Shards, 1X T5 Ghast, 1X T5 Endermen, 1X T5 Wither Skeleton, 1X T5 Vindicator (if unable to spawn t5 shards I will accept mob imprisonment tools with said mobs listed along with unused soul shards)
1X Soul Cage
1X Reinforced Integral Component
1X Flux Controller
1X Flux Wrench
3X Flux Plugs
4X Flux Points
6X Mob Imprisonment Tools, 1X with a captured Evoker
3X Ancient Debris
2X stacks of Tinted Glass from Mob Grinding Utils

**Comment by john01dav** [comment]
At what coordinates would you like this to be dropped off?

**Comment by H20Slicer** [comment]
> At what coordinates would you like this to be dropped off?

Sorry John, I forgot to close this after you refunded me my stuff.
