### ISSUE TITLE
Bugged quest #142

### ISSUE THREAD

**Issue by Lagarex** [ModdedMinecraftClub/issue-tracker#7]
Quest for Personal Shrinking device keeps getting bugged with -time make /kit for it instead?

Looks like reset of server makes it work for one time again.

**Comment by Duckgrass** [comment]
I toggled edit mode on and then off since that might fix it. Let me know if the issue still persists and I'll investigate further.

**Comment by TraceLD** [comment]
I'm closing for now, if the issue reappears or it hasn't been fixed, please comment here and reopen the issue.
