### ISSUE TITLE
DW20 1.18 Grave Recovery

### ISSUE THREAD

**Issue by BDJslime-UnaverageJoe** [ModdedMinecraftClub/issue-tracker#72]
![2022-07-06_22 14 10](https://user-images.githubusercontent.com/77141332/177699682-f772d0b2-0885-4c78-85ce-c6d332b9a39a.png)
So the game decides to be screwy with me and summons a champion boss with shielding, meaning I can't use a bow to defeat it quickly.
![2022-07-06_22 35 17](https://user-images.githubusercontent.com/77141332/177699706-bd947628-b5c0-419e-9905-8542dc9251a9.png)
That causes me to have to die a lot in order to defeat the boss, and with a lot of graves comes a chance of deleing the one with my items, I have saved 2 Obutiutary stating the ID containing the items that I originally have
![2022-07-06_22 39 03](https://user-images.githubusercontent.com/77141332/177699707-79e0263e-5c9d-42a2-8cc9-3559244a6a91.png)
![2022-07-06_22 39 05](https://user-images.githubusercontent.com/77141332/177699715-80c45003-df39-4ab7-9007-fcb534e42c1b.png)

**Comment by john01dav** [comment]
Done
