### ISSUE TITLE
Unintended Interaction: GraveStone and Progressive Bosses

### ISSUE THREAD

**Issue by n33tfr33k** [ModdedMinecraftClub/issue-tracker#74]
I would like to propose a change to the GraveStone mod configuration on DW.

Currently if you die while near an Ocean Monument your items cannot be recovered until all Elder Guardians are killed due to Progressive Bosses mod as it prevents you from breaking blocks, including your grave.

There is a relevant issue in the FTB issue tracker:
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/849

The FTB devs do not see this as an issue that needs to be addressed and instead suggested that it be handled at the server instance level via the following configuration change:

In: gravestone-server.toml

#If this is set to true you get your items back into your inventory by sneaking on the grave
sneak_pickup = false

This change would not remove the challenge added by Progressive Bosses. 

This has happened twice in the last two days and would greatly reduce frustration if this change could be implemented on the mmc DW server. 

Thank you for your consideration.

**Comment by merx3d** [comment]
changed to true, sorry for delay, working though issues to close them all
