### ISSUE TITLE
Mekanism Ore Processing missing ores

### ISSUE THREAD

**Issue by Turkminaiter** [ModdedMinecraftClub/issue-tracker#76]
Silver ore, Nickel ore and Aluminium ore dont work with the Mekanism ore processing.
The one where you turn it in to ore slurry. 
Most other ores do work. Like Iron, Gold, Copper, Tin, Lead and Uranium.

**Comment by merx3d** [comment]
not sure if this is a recipe easily tweaked on our end

**Comment by Tenchu98** [comment]
generally speaking we don't add compatibility ourselves, it's best to report it to the pack dev, in case they made it intentional.
