### ISSUE TITLE
Admins literally can't do admin work

### ISSUE THREAD

**Issue by TraceLD** [ModdedMinecraftClub/issue-tracker#8]
Literally can't bypass literal claims

**Comment by TraceLD** [comment]
I also can't change permissions myself because I don't know where they are in the dir structure

**Comment by RaVenInTheDark** [comment]
> Literally can't bypass literal claims

There's a command that you can run when opped. `/ftbchunks admin bypass_protection` or something along those lines.

**Comment by john01dav** [comment]
The command that raven gave works, so I'm closing this issue.

**Comment by TraceLD** [comment]
Hiagg literally boddied by Raven on modded minecraft knowledge. I'm floored.

**Comment by RaVenInTheDark** [comment]
> Hiagg literally boddied by Raven on modded minecraft knowledge. I'm floored.

It's daily routine.
