### ISSUE TITLE
Save Spice of Life Extra Hearts

### ISSUE THREAD

**Issue by BDJslime-UnaverageJoe** [ModdedMinecraftClub/issue-tracker#82]
```
[miscellaneous]
	#Whether or not to reset the food list on death, effectively losing all bonus hearts.
	resetOnDeath = true
```
Just why?
I do not know why the ATM team chose to enable this but it is very frustrating to have on.

**Comment by Tenchu98** [comment]
As a general rule we don't change settings from their default unless they effect server performance. I can mention it to the rest of staff and get their opinions though.
