### ISSUE TITLE
Base section restore

### ISSUE THREAD

**Issue by SusanS2022** [ModdedMinecraftClub/issue-tracker#84]
game name: michaels84
login time: 20:18 NZ time

Greetings.
I am somewhat hoping I might be able to get a restore of my base or at the least the chunk surrounding 16662, -19164.
I have had my fluid nuke over heat on me with my remote temp control not trigger to stop it.

The blast took out my back up nuke as well leaving my base not powerable.
looked to be a 3x3 chunk but looks to of also made it to my heat exchanger.

thank-you for your time.

**Comment by Duckgrass** [comment]
What are the cords and when exactly did it blow up?

**Comment by SusanS2022** [comment]
More accurate coords.Between 16641 x -19168 and 16687 x -19137Might be easier to do the chunks from what I know of world edit.On 1/08/2022 06:34, Michael Sparrow ***@***.***> wrote:I think the chords i provided were in the general location of the blast. If you need exact chords, I'll have to log in. Happened around 9pm nzt.On 1/08/2022 05:11, Duckgrass ***@***.***> wrote:
What are the cords and when exactly did it blow up?

**Comment by Duckgrass** [comment]
I restored the whole region file from the backup which should be the nearest to the point of the explosion.
Logging on it seems to be in a proper state, but let me know what it seems to you.
I also disabled the redstone line to the reactor by breaking a couple redstone wiring just to be safe.

**Comment by SusanS2022** [comment]
Yes that worked perfectly thankyou. Quick note, was the wrong nuke that you disabled. Luckily it was switched off at time of the log. The standard nuke was stable to run.Is a shame I left my avatar in the hole as I suffocated in the wall on logging in.On 1/08/2022 13:22, Duckgrass ***@***.***> wrote:
I restored the whole region file from the backup which should be the nearest to the point of the explosion.
Logging on it seems to be in a proper state, but let me know what it seems to you.
I also disabled the redstone line to the reactor by breaking a couple redstone wiring just to be safe.

**Comment by SusanS2022** [comment]
I think the chords i provided were in the general location of the blast. If you need exact chords, I'll have to log in. Happened around 9pm nzt.On 1/08/2022 05:11, Duckgrass ***@***.***> wrote:
What are the cords and when exactly did it blow up?
