### ISSUE TITLE
Chunk Rollback needed - Reactor popped

### ISSUE THREAD

**Issue by Boross92** [ModdedMinecraftClub/issue-tracker#88]
IGN: Boross92
My Base co-ords are: -1130, 76, -743.
Time to reset to is 5pm GMT on 18.08.2022 (check Discord chat log for the moment when I said my reactor blew up. It was at ~5:10pm. So a time before that would be ideal.

Reactor will need to be turned off once chunk rollback is successful.
Thanks!

**Comment by Tenchu98** [comment]
Fair warning, as a general rule Rollback are for corruption. Moderators can choose to offer a Rollback in other instances, but destroying your base is one of the inbuilt risks of using a reactor.

**Comment by merx3d** [comment]
So, I tried to roll it back an hour then 2 hours and both had the reactor blown so how far back are you comfortable with me going?

**Comment by merx3d** [comment]
stale issue, tried to rollback 12 hours, the resulting region was still popped, the backups from that time might've been deleted.
