### ISSUE TITLE
IC2 crop sticks are unable to be placed in the overworld. 

### ISSUE THREAD

**Issue by ashido96** [ModdedMinecraftClub/issue-tracker#89]
GT:NH bugtracker: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10879

GT:NH server admin boubou19: "basically, i crashed the server" "i moved the server from thermos to forge temporarily, i derped in the process, i reverted to previous installation, and the bug was gone" "trust me, i try to track this bug down since 6 years now"
"it's really frustrating that i got the bug to go away with a random crash. I don't even know if it's a coincidence or if it really helped"

This bug has been present on the GTNH ironman server since approximately Aug. 8th 2022

**Comment by Duckhemp** [comment]
I need to dig more into the issue. Someone found a temp solution of it working in the twilight forest.
