### ISSUE TITLE
Chunk Rollback - Missing Items - RBurgandy - A7

### ISSUE THREAD

**Issue by Bishnu82** [ModdedMinecraftClub/issue-tracker#92]
My original had no label so resubmitting with label.

IGN - RBurgandy

My cords are 4085, 4533 and the time was around 8:57 - 9AM EST on 8/23/2022.

Just got my first Anti Matter pellet and was making the largest QIO drive. The server timed out why I had the items in the crafting table. So the 4 QIO drives that had all my stuff plus 4 lead bars and the Anti Matter are gone. I lost everything except my base. I was hoping you could restore my 4 drives that had all my stuff on it and the Anti Matter. Was talking to someone and they said it might be a chunk rollback.

**Comment by Duckhemp** [comment]
We have rollbacked your base and see the 4 drives in the drive bay. I have also carried over your newer 1k drive. 
Let us know if anything is missing that you made progress on, and we will try refunding it or look into merging the rollback and current region.
