### ISSUE TITLE
Chunk Rollback - Tried to read NBT tag that was to big

### ISSUE THREAD

**Issue by Bishnu82** [ModdedMinecraftClub/issue-tracker#93]
IGN - RBurgandy

My cords are 4085, 4533 and the time was around 8:57 - 9AM EST on 8/23/2022.

![image](https://user-images.githubusercontent.com/55993943/187209105-4012bd57-2c54-42fe-93e3-87cfe957c73c.png)

This is related to this issue https://github.com/ModdedMinecraftClub/issue-tracker/issues/92

For some reason when I make the large QIO drive I get this error and cant access my stuff.  I as hoping you could do the same thing you did before in the linked ticket above.  I figure if I make the new QIO drive without my 4 that have things on it it will be empty and I can then just move my stuff over without this problem.  I also might need you to remove the Supermassive QIO drive from my inventory if possible.  Whenever I click it I get that error.

**Comment by Tenchu98** [comment]
Maybe it's time to move away from qio and into rs or ae2.

**Comment by Bishnu82** [comment]
Yeah this is all new to me.  The reason I picked this mod pack to play was I knew a bit about Mekanism.  I will look into those other 2 systems would you recommend one over the other?

**Comment by Tenchu98** [comment]
Rs is easier for beginners, ae2 is a bit more technical and you have to mind channels
