### ISSUE TITLE
"Unexpected custom data from client" when joining server

### ISSUE THREAD

**Issue by Freykii** [ModdedMinecraftClub/issue-tracker#96]
Hello,
i said it all in the title. I downloaded the 0.4.29 All the Mods 7 at the Curse page (I verified that i got the right version and not the last released). I downloaded manually all the mods that made an error (I am using PolyMC 1.4.2)

**Comment by Tenchu98** [comment]
please upload your log to pastebin and post the link here so we can look at the specific error.

**Comment by Tenchu98** [comment]
also what do you mean you downloaded the mods manually?
you have to download the pack as a whole in order to get all the custom items in the pack.

**Comment by Freykii** [comment]
> also what do you mean you downloaded the mods manually? you have to download the pack as a whole in order to get all the custom items in the pack.

In PolyMC i had an error telling me he couldn't DL properly the mods and i had to get them by myself by a link, so i did.
I had the same thing on Enigmatica 8 but the modpack worked properly

**Comment by Freykii** [comment]
> please upload your log to pastebin and post the link here so we can look at the specific error.

I dont find any in the "Minecraft" folder from PolyMC

**Comment by Freykii** [comment]
> > also what do you mean you downloaded the mods manually? you have to download the pack as a whole in order to get all the custom items in the pack.
> 
> In PolyMC i had an error telling me he couldn't DL properly the mods and i had to get them by myself by a link, so i did. I had the same thing on Enigmatica 8 but the modpack worked properly

If i remember well it was 4 mods

**Comment by Tenchu98** [comment]
There should be a logs folder inside the instance folder, then you upload latest.log
I have not used polyMC so I can't direct anything for searching.

**Comment by Freykii** [comment]
There isn't any.... I manually checked and i also tried the "log" in the search bar.
I am gonna try with GDLauncher

**Comment by Tenchu98** [comment]
Unless polymc is deleting it for some reason it would have to exist, also gdlauncher is significantly better for downloading modpack because it will manually download the specified file itself.

**Comment by Freykii** [comment]
Okey, thank you anyway for the help.
The strangest thing is that in my other instances i got a log file but not in PolyMC... I'll try to make PolyMC create one so you can help people in the future with that issue.

**Comment by Freykii** [comment]
I have something else now. I reinstalled the modpack with PolyMC and when i try to connect to the server i have "Failed to connect to the server - Disconnected". 
I took the EU/Asia IP because i'm in France.

**Comment by Freykii** [comment]
[latest.log](https://github.com/ModdedMinecraftClub/issue-tracker/files/9639684/latest.log)

**Comment by Tenchu98** [comment]
yeah it is going to do that because you are missing mods according to the log you uploaded
Server has additional mods that may be needed on the client: hexerei@0.2.2, chunkpregen@1.18-4.0.2, insane_sane_shutdown@1.0, eccentrictome@0.0NONE, plg7472616365@1.0.0, experiencebugfix@1.38.0.2

**Comment by Freykii** [comment]
I just tried with the GD Launcher and i got the "Failed to connect to the server - Disconnected" message...

**Comment by Freykii** [comment]
Why does the server has additionnal mods and no one told it ?

**Comment by Tenchu98** [comment]
The server has additional mods because some of the mods are tagged to only be downloadable through the curse launcher. With gdlauncher you have to make sure to let it do it's thing the whole way through downloading the pack. It will open a new window for each of those mods and manually download them into the mod folder.
