### ISSUE TITLE
GriefPreventation is blocking OpenComputers from working

### ISSUE THREAD

**Issue by Emiralp26** [ModdedMinecraftClub/issue-tracker#98]
Hello,

I have spent a small fortune and some time trying to set up a computer and have got everything set up however, due to the griefpreventation plugin I am unable to fulfill my objective with the computer as the plugin blocks interaction between the transposer and the containers. I have tried to do /trust [OpenComputers], however, to no avail is there anything that can be done about this situation? (This I for Gregtech Ironman)

Kind Regards,
emi

**Comment by merx3d** [comment]
So there is a whitelist for always trusted players, however my concern would be someone abusing that to damage other people's claims.

**Comment by Emiralp26** [comment]
I am unsure of what the best course of action would be however I am strongly in favor of allowing people to do OpenComputers without having to fiddle with your claim every time.

> So there is a whitelist for always trusted players, however my concern would be someone abusing that to damage other people's claims.

**Comment by merx3d** [comment]
I might reach out to you when I have a good bit of free time to help in testing if forcefully trusting opencomputers globally allows interaction when it's acting on other player's claims. I however don't want to jump the gun on it and just enable it outright without supervision.

**Comment by Emiralp26** [comment]
Feel free to reach out to me when ever you are available we can arrange a time to test things out. My discord is emi#5440

**Comment by merx3d** [comment]
closing for now, will look into when emi returns or if request reoccurs, and solution can be identified
